# These are supported funding model platforms

#github: acctgen1
patreon: acctgen1
custom: ["https://www.buymeacoffee.com/", BuymyaCoffee.com]
# <!--custom: ["https://www.paypal.me/octocat", octocat.com]-->
